# Site Configuration

title: Alpha18 Engineering Design
email: elviskasonlin.17@ichat.sp.edu.sg
description: >-  This site details the entire journey undertaken by the team as part of the Engineering Design module to create a sensor platform.
baseurl: "/project" # the subpath of your site, e.g. /blog
url: "localhost:4000" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: "" 
github_username: "" 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
